name: Checkov IaC Scanning

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          quiet: true